# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gd2-ffi}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Patrik Stenmark"]
  s.date = %q{2009-08-05}
  s.description = %q{gd2-ffi is ruby bindings for gd2, implemented with ffi}
  s.email = %q{patrik.stenmark@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "VERSION",
     "gd2-ffi.gemspec",
     "lib/gd2-ffi.rb",
     "lib/gd2/canvas.rb",
     "lib/gd2/cgd2.rb",
     "lib/gd2/color.rb",
     "lib/gd2/font.rb",
     "lib/gd2/image.rb",
     "spec/Vera.ttf",
     "spec/canvas_spec.rb",
     "spec/color_spec.rb",
     "spec/image_spec.rb",
     "spec/spec_helper.rb",
     "test.rb"
  ]
  s.homepage = %q{http://github.com/spatrik/gd2-ffi}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{gd2-ffi is ruby bindings for gd2, implemented with ffi}
  s.test_files = [
    "spec/canvas_spec.rb",
     "spec/color_spec.rb",
     "spec/image_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
